[project]
name = "python-api-tests"
version = "0.1.0"
description = ""
authors = [
    {name = "Denis Chudnov PC",email = "denis.chudnov.97@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "allure-pytest (>=2.16.0,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[tool.poetry]
packages = [{include = "python_api_tests", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
